2025-03-27 05:09:23,406 - INFO: Fragrantica'da bottled absolu için arama yapýlýyor
2025-03-27 05:09:23,602 - ERROR: Request hatasý (Deneme 1/3): 403 Client Error: Forbidden for url: https://www.fragrantica.com/search/?query=bottled+absolu
2025-03-27 05:09:24,615 - INFO: Rate limiting: 0.80 saniye bekleniyor
2025-03-27 05:09:25,589 - ERROR: Request hatasý (Deneme 2/3): 403 Client Error: Forbidden for url: https://www.fragrantica.com/search/?query=bottled+absolu
2025-03-27 05:09:27,794 - ERROR: Request hatasý (Deneme 3/3): 403 Client Error: Forbidden for url: https://www.fragrantica.com/search/?query=bottled+absolu
2025-03-27 05:09:27,821 - ERROR: Traceback (most recent call last):
  File "c:\Users\muozez\Desktop\Yazýlým\denemeqr\request.py", line 78, in safe_request
    response.raise_for_status()  # HTTP hatalarý için
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\muozez\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://www.fragrantica.com/search/?query=bottled+absolu

2025-03-27 05:09:27,821 - ERROR: Fragrantica arama hatasý: Request baþarýsýz: 403 Client Error: Forbidden for url: https://www.fragrantica.com/search/?query=bottled+absolu
2025-03-27 05:09:27,821 - ERROR: Traceback (most recent call last):
  File "c:\Users\muozez\Desktop\Yazýlým\denemeqr\request.py", line 78, in safe_request
    response.raise_for_status()  # HTTP hatalarý için
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\muozez\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://www.fragrantica.com/search/?query=bottled+absolu

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\muozez\Desktop\Yazýlým\denemeqr\request.py", line 98, in search_fragrantica
    response = self.safe_request(search_url)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\muozez\Desktop\Yazýlým\denemeqr\request.py", line 88, in safe_request
    raise ParfumScraperException(f"Request baþarýsýz: {e}")
ParfumScraperException: Request baþarýsýz: 403 Client Error: Forbidden for url: https://www.fragrantica.com/search/?query=bottled+absolu

2025-03-27 05:12:40,619 - INFO: Fragrantica'da bottled absolu için arama yapýlýyor
2025-03-27 05:12:43,997 - ERROR: Ýstek hatasý (Deneme 1): HTTPSConnectionPool(host='www.fragrantica.com', port=443): Max retries exceeded with url: /search/?query=bottled+absolu (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 308 Permanent Redirect')))
2025-03-27 05:12:57,210 - ERROR: Ýstek hatasý (Deneme 2): HTTPSConnectionPool(host='www.fragrantica.com', port=443): Max retries exceeded with url: /search/?query=bottled+absolu (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001F94A89A570>, 'Connection to 185.233.37.83 timed out. (connect timeout=10)')))
2025-03-27 05:13:11,128 - ERROR: Ýstek hatasý (Deneme 3): HTTPSConnectionPool(host='www.fragrantica.com', port=443): Max retries exceeded with url: /search/?query=bottled+absolu (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001F94A89AB10>, 'Connection to 185.230.105.226 timed out. (connect timeout=10)')))
2025-03-27 05:13:18,182 - ERROR: Ýstek hatasý (Deneme 4): HTTPSConnectionPool(host='www.fragrantica.com', port=443): Max retries exceeded with url: /search/?query=bottled+absolu (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 308 Permanent Redirect')))
2025-03-27 05:13:39,096 - ERROR: Ýstek hatasý (Deneme 5): HTTPSConnectionPool(host='www.fragrantica.com', port=443): Max retries exceeded with url: /search/?query=bottled+absolu (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001F94A89A900>, 'Connection to 185.230.105.226 timed out. (connect timeout=10)')))
2025-03-27 05:13:55,098 - ERROR: Tüm deneme giriþimleri baþarýsýz oldu.
2025-03-27 05:23:46,030 - ERROR: Tüm deneme giriþimleri baþarýsýz oldu.
2025-03-27 05:27:55,838 - INFO: Parfüm detaylarý çekiliyor: https://www.parfumo.com/Perfumes/Dior/Sauvage_Eau_de_Toilette
2025-03-27 05:27:57,054 - INFO: Çekilen parfüm detaylarý: {'parfum_adi': 'Sauvage Dior 2015 Eau de Toilette', 'ana_akorlar': [], 'notalar': [], 'parfumor': 'Bilinmiyor', 'yayin_yili': 'Bilinmiyor', 'link': 'https://www.parfumo.com/Perfumes/Dior/Sauvage_Eau_de_Toilette'}
